"use client"
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/fragments/Header"
import Footer from "@/components/fragments/Footer"
import { usePathname } from "next/navigation";
import ArrowBack from "@/components/UI/ArrowBack";
import { Provider } from "./provider";

const disableHeaderFooter = ["/login", "/register"]
// export const metadata: Metadata = {
//   title: "Jatrip Explore Jatim",
//   description: "Generated by create next",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en" className="overflow-x-hidden">
      <Provider>
        <body>
          {!disableHeaderFooter.includes(pathname) ? <Header /> : <ArrowBack />}
          {children}
          {!disableHeaderFooter.includes(pathname) && <Footer />}
        </body>
      </Provider>
    </html>
  );
}
