import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/fragments/Header"
import Footer from "@/components/fragments/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jatrip Explore Jatim",
  description: "Generated by create next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
